{{- if and .Values.nifi.properties.secured ( and .Values.nifi.authentication.ldap.enabled .Values.nifi.authentication.ldap.tls.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nifi.fullname" . }}-ldap-certs
  labels:
    app: {{ include "nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{ if .Values.nifi.authentication.ldap.tls.certs.wildcard }}
    {{- $ca_certificate := printf "%s/%s" .Values.nifi.authentication.ldap.tls.certs.dir .Values.nifi.authentication.ldap.tls.certs.caCertificate }}
    ca_certificate: {{ (.Files.Get $ca_certificate) | b64enc | quote }}
    {{- $certificate := printf "%s/%s" .Values.nifi.authentication.ldap.tls.certs.dir .Values.nifi.authentication.ldap.tls.certs.certificate }}
    certificate: {{ (.Files.Get $certificate) | b64enc | quote }}
    {{- $private_key := printf "%s/%s" .Values.nifi.authentication.ldap.tls.certs.dir .Values.nifi.authentication.ldap.tls.certs.privateKey }}
    private_key: {{ (.Files.Get $private_key) | b64enc | quote }}
{{ end }}
{{ end }}
