---
# We would create a service-account for accessing the pods from within other pods of the cluster
# Service acount creation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nifi.fullname" . }}

---
# Role creation
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "nifi.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
{{- if and .Values.ingress.enabled (and .Values.nifi.properties.secured .Values.nifi.tls.certificateSource.nifiToolkit) }}
      # We would require to upload the certificate for proxy when using nifi-toolkit as CA
      - secrets
{{- end }}
    verbs:
      - get
      - create

---
# Role binding between service-account and role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "nifi.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nifi.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "nifi.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

