---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ca.fullname" . }}
  labels:
    app: {{ template "ca.name" . }}-ca
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ca.name" . }}-ca
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ca.name" . }}-ca
        release: {{ .Release.Name }}
    spec:
{{- if .Values.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecret }}
{{- end }}
      containers:
      - name: ca
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - sh
        - -c
        - |
          exec ${NIFI_TOOLKIT_HOME}/bin/tls-toolkit.sh server -c "{{ template "ca.fullname" . }}" -t {{ .Values.token }} -p {{ .Values.app_port }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.app_port }}
        livenessProbe:
          initialDelaySeconds: 90
          periodSeconds: 60
          tcpSocket:
            port: {{ .Values.app_port }}
      terminationGracePeriodSeconds: 0