name: Build/Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Gradle Build
      run: ./gradlew compileJava
    - name: Gradle Test
      run: ./gradlew test
    - name: Gradle create shadowJar
      run: ./gradlew shadowJar
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag microsoft/dagx:$(date +%s)
