name: Build/Test

on: [ push ]

jobs:
  verify:
    runs-on: ubuntu-latest

    services:
      nifi:
        image: apache/nifi
        ports:
          - 8080:8080
          - 8888:8888

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Gradle compile
        run: ./gradlew compileJava

      - name: Gradle Test
        env:
          AZ_STORAGE_KEY: ${{ secrets.AZ_STORAGE_KEY }}
          NIFI_API_AUTH: ${{ secrets.NIFI_API_AUTH }}
        run: ./gradlew test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml
